Repository ZPI-UKW/zpi-front-end, pull requests merged in 2021-05, with the labels that each got.

#14 Sign in and sign up modal
  package-lock.json
  package.json
  src/components/AuthDialog/dialog.tsx
  src/components/AuthDialog/dialogContent.tsx
  src/components/AuthDialog/dialogTitle.tsx
  src/components/AuthDialog/styles.tsx
  src/components/AuthDialog/types.ts
  src/components/Forms/passwordField.tsx
  src/components/Forms/signinForm.tsx
  src/components/Forms/signupForm.tsx
  src/components/Forms/styles.ts
  src/hooks/useRect.ts
  src/templates/Header/desktop.tsx
  src/templates/Header/index.tsx
  src/templates/Header/mobile.tsx
  src/templates/Header/types.ts
  src/validation/AuthSchema.ts
Labels: enhancement

#15 Card component, my rentals and my annoucements view
  src/components/CardsContainer/cardsContainer.ts
  src/components/ProductCard/card.tsx
  src/components/ProductCard/types.ts
  src/context/authContext.tsx
  src/context/types.ts
  src/data/annoucements.ts
  src/views/MyAnnoucements/myAnnoucements.tsx
  src/views/MyRentals/myRentals.tsx
  src/views/Root.tsx
Labels: enhancement

#16 #5 Main page
  package-lock.json
  package.json
  src/components/Category/categories.data.ts
  src/components/Category/category.interface.ts
  src/components/Category/icon.types.ts
  src/components/Category/index.tsx
  src/components/Category/styles.ts
  src/templates/Header/index.tsx
  src/templates/Wrapper/index.tsx
  src/templates/Wrapper/styles.ts
  src/theme/globalStyles.ts
  src/views/Main/index.tsx
  src/views/Main/styles.ts
  src/views/Root.tsx
Labels: enhancement

#17 Create and edit views
  package-lock.json
  package.json
  src/components/AuthDialog/dialog.content.tsx
  src/components/AuthDialog/dialog.tsx
  src/components/AuthDialog/dialogTitle.tsx
  src/components/DialogTitle/index.tsx
  src/components/Forms/Annocement/annoucement.cropper.tsx
  src/components/Forms/Annocement/annoucement.textfields.tsx
  src/components/Forms/Annocement/annoucement.util.ts
  src/components/Forms/Annocement/index.tsx
  src/components/Forms/Annocement/styles.ts
  src/components/Forms/Annocement/types.ts
  src/components/ProductCard/card.tsx
  src/components/ViewContainer/index.tsx
  src/components/ViewTitle/index.tsx
  src/data/annoucements.ts
  src/views/AnnoucementForm/index.tsx
  src/views/MyAnnoucements/index.tsx
  src/views/MyAnnoucements/styles.ts
  src/views/MyRentals/myRentals.tsx
  src/views/Root.tsx
Labels: bug, enhancement

#20 19-Mobile-view
  src/components/AddAnnouncementBtn/index.tsx
  src/components/AddAnnouncementBtn/styles.ts
  src/components/CardsContainer/cardsContainer.ts
  src/components/CardsContainer/index.tsx
  src/components/ProductCard/card.tsx
  src/components/ViewContainer/index.tsx
  src/views/MyAnnoucements/index.tsx
  src/views/MyRentals/myRentals.tsx
Labels: enhancement

#23 Create product view
  package-lock.json
  package.json
  src/components/Annoucement/annoucement.slider.tsx
  src/components/Annoucement/index.tsx
  src/components/Annoucement/styles.ts
  src/components/Annoucement/types.ts
  src/views/Product/index.tsx
  src/views/Product/styles.ts
  src/views/Product/types.ts
  src/views/Root.tsx
Labels: enhancement

#22 Connect sign in and sign up form with backend
  package-lock.json
  package.json
  src/components/AuthDialog/dialog.content.tsx
  src/components/AuthDialog/dialog.tsx
  src/components/AuthDialog/types.ts
  src/components/CustomControls/masked.control.tsx
  src/components/CustomControls/password.control.tsx
  src/components/CustomControls/types.ts
  src/components/Forms/SignIn/index.tsx
  src/components/Forms/SignIn/signin.datacontrol.tsx
  src/components/Forms/SignIn/types.ts
  src/components/Forms/SignUp/index.tsx
  src/components/Forms/SignUp/signup.datacontrol.tsx
  src/components/Forms/SignUp/types.ts
  src/components/Forms/signinForm.tsx
  src/components/Forms/styles.ts
  src/context/authContext.tsx
  src/context/helpers.ts
  src/context/types.ts
  src/graphql/auth.ts
  src/templates/Main/index.tsx
  src/templates/Main/styles.ts
  src/types/global.ts
  src/validation/AuthSchema.ts
Labels: bug, enhancement

#25 Create rent dialog
  package-lock.json
  package.json
  src/components/Annoucement/index.tsx
  src/components/Annoucement/styles.ts
  src/components/CustomControls/datepicker.control.tsx
  src/components/CustomControls/types.ts
  src/components/DialogTitle/index.tsx
  src/components/DialogTitle/styles.tsx
  src/components/DialogTitle/types.ts
  src/components/Navigation/index.tsx
  src/components/Navigation/styles.ts
  src/components/Navigation/transition.tsx
  src/components/Navigation/types.ts
  src/components/RentDialog/index.tsx
  src/components/RentDialog/pricing.rentmodal.tsx
  src/components/RentDialog/styles.ts
  src/components/RentDialog/types.ts
  src/components/SpinnerButton/index.tsx
  src/components/SpinnerButton/styles.ts
  src/components/SpinnerButton/types.ts
  src/templates/Header/desktop.tsx
  src/templates/Header/mobile.tsx
  src/templates/Main/index.tsx
  src/theme/globalStyles.ts
  src/theme/material-theme.ts
  src/types/material.ts
Labels: cleanup, enhancement

#27 Create profile page connected to backend
  package-lock.json
  package.json
  src/components/CustomControls/password.control.tsx
  src/components/CustomControls/styles.ts
  src/components/CustomControls/types.ts
  src/components/DataControl/index.tsx
  src/components/Forms/ChangePassword/index.tsx
  src/components/Forms/ChangePassword/styles.ts
  src/components/Forms/ChangePassword/types.ts
  src/components/Forms/ChangeUserData/index.tsx
  src/components/Forms/ChangeUserData/styles.ts
  src/components/Forms/SignIn/signin.datacontrol.tsx
  src/components/Forms/SignIn/types.ts
  src/components/Forms/styles.ts
  src/graphql/auth.ts
  src/graphql/user.ts
  src/hooks/useGraphql/types.ts
  src/hooks/useGraphql/useGraphql.tsx
  src/types/global.ts
  src/validation/modifyuserdata.validation.ts
  src/validation/shared.validation.ts
  src/views/Profile/index.tsx
  src/views/Profile/styles.ts
  src/views/Root.tsx
Labels: enhancement, refactoring
