Repository ZPI-UKW/zpi-front-end, pull requests merged in 2021-06, with the labels that each got.

#28 Feat/12 list of announcements
  package-lock.json
  package.json
  src/assets/undraw_searching_p5ux.svg
  src/components/CardsContainer/index.tsx
  src/components/Category/styles.ts
  src/components/Search/index.tsx
  src/components/Search/styles.ts
  src/components/ViewContainer/index.tsx
  src/react-app-env.d.ts
  src/views/AnnouncementsList/index.tsx
  src/views/AnnouncementsList/styles.ts
  src/views/Main/index.tsx
  src/views/Main/styles.ts
  src/views/Root.tsx
Labels: enhancement

#33 Improvements
  src/components/AuthRoute/index.tsx
  src/components/AuthRoute/types.ts
  src/components/Forms/Annocement/annoucement.textfields.tsx
  src/components/Forms/Annocement/annoucement.util.ts
  src/components/Forms/Annocement/styles.ts
  src/components/Forms/Annocement/types.ts
  src/components/Forms/ChangePassword/index.tsx
  src/components/Forms/ChangeUserData/index.tsx
  src/components/Forms/ChangeUserData/types.ts
  src/context/authContext.tsx
  src/context/types.ts
  src/graphql/user.ts
  src/templates/Header/desktop.tsx
  src/views/Root.tsx
Labels: enhancement

#35 Using Google maps API and refactoring some code
  package-lock.json
  package.json
  src/components/Forms/Annocement/annoucement.control.tsx
  src/components/Forms/Annocement/annoucement.file.tsx
  src/components/Forms/Annocement/annoucement.location.tsx
  src/components/Forms/Annocement/annoucement.textfields.tsx
  src/components/Forms/Annocement/annoucement.util.ts
  src/components/Forms/Annocement/index.tsx
  src/components/Forms/Annocement/styles.ts
  src/components/Forms/Annocement/types.ts
  src/components/Forms/ChangePassword/index.tsx
  src/components/Forms/ChangePassword/styles.ts
  src/components/Forms/ChangeUserData/index.tsx
  src/components/Forms/ChangeUserData/styles.ts
  src/components/Forms/SignIn/index.tsx
  src/components/Forms/SignIn/signin.datacontrol.tsx
  src/context/locationContext/locationContext.tsx
  src/context/locationContext/types.ts
  src/templates/Main/index.tsx
Labels: cleanup, enhancement, refactoring

#36 Connect with backend
  src/components/AddAnnouncementBtn/styles.ts
  src/components/Annoucement/index.tsx
  src/components/Annoucement/styles.ts
  src/components/Annoucement/types.ts
  src/components/ErrorMessage/index.tsx
  src/components/ErrorMessage/styles.ts
  src/components/ErrorMessage/types.ts
  src/components/Forms/Annocement/annoucement.util.ts
  src/components/RentDialog/index.tsx
  src/components/RentDialog/types.ts
  src/context/authContext.tsx
  src/data/annoucements.ts
  src/graphql/annoucements.ts
  src/templates/Header/desktop.tsx
  src/views/AnnouncementsList/index.tsx
  src/views/MyAnnoucements/index.tsx
  src/views/MyAnnoucements/types.ts
  src/views/MyRentals/index.tsx
  src/views/MyRentals/myRentals.tsx
  src/views/MyRentals/types.ts
  src/views/Product/index.tsx
  src/views/Product/types.ts
  src/views/Root.tsx
Labels: enhancement

#43 Connect edit/add annoucement form with backend
  src/components/CustomControls/masked.control.tsx
  src/components/CustomControls/types.ts
  src/components/Forms/Annocement/annoucement.control.tsx
  src/components/Forms/Annocement/annoucement.location.tsx
  src/components/Forms/Annocement/annoucement.textfields.tsx
  src/components/Forms/Annocement/annoucement.util.ts
  src/components/Forms/Annocement/index.tsx
  src/components/Forms/Annocement/styles.ts
  src/components/Forms/Annocement/types.ts
  src/components/Navigation/index.tsx
  src/components/Navigation/types.ts
  src/graphql/annoucement.ts
  src/graphql/user.ts
  src/templates/Header/desktop.tsx
  src/templates/Header/index.tsx
  src/templates/Header/mobile.tsx
  src/templates/Header/types.ts
  src/validation/annoucement.validation.ts
  src/validation/shared.validation.ts
  src/views/AnnouncementsList/index.tsx
Labels: enhancement

#44 Refactor signup form
  src/components/Forms/SignIn/index.tsx
  src/components/Forms/SignUp/index.tsx
  src/components/Forms/SignUp/signup.datacontrol.tsx
  src/components/Forms/styles.ts
  src/hooks/useGraphql/useGraphql.tsx
Labels: enhancement, refactoring

#48 Build/47 create environment variables
  README.md
  package-lock.json
  package.json
  src/environments/.env
  src/templates/Main/index.tsx
Labels: enhancement
